name: Run ML Backend

on:
  workflow_dispatch:

  schedule:
    - cron: '0 13 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          cd Movil/ml_backend
          pip install -r requirements.txt

      - name: Crear credenciales Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Ejecutar entrenamiento
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json
        run: |
          cd Movil/ml_backend
          python train_two_tower.py --train
